### ISSUE TITLE
[Dungeon] Lower Blackrock Spire - Scarshield Warlock - Abilities

### ISSUE THREAD

**Issue by whammyresilience** [NoxGaming/TrinityCore#103]
**Current behaviour:**

[Scarshield Warlock's](https://classicdb.ch/?npc=9257#abilities) ability, [Scarshield Portal](https://classicdb.ch/?spell=15125), doesn't summon any minions.

**Expected behaviour:**

Possible expected behavior?
>The warlocks open a portal that summons imps. A portal was open and a couple of imps had come through, and then a felguard came through. The strange thing was that is was a rare spawn (not named, but had the silver dragon around the portrait). The rare spawn dropped a pair of BOE mail gloves.

**Steps to reproduce the problem:**

1. Start combat with a warlock
2. Watch it cast the portal spell
3. Watch the portal do nothing and disappear.

**Comment by Cillez** [comment]
Can confirm

Here's the fix:

``````-- Scarshield Warlock, Scarshield Portal fix
Update smart_scripts set `event_param1` = 30000 where `entryorguid` = 9707 and `ID` = 3;
Update smart_scripts set `event_param2` = 30000 where `entryorguid` = 9707 and `ID` = 3;
Update smart_scripts set `event_type` = 1 where `entryorguid` = 9707;
Update smart_scripts set `event_param3` = 10000 where `entryorguid` = 9707 and `ID` = 0;
Update smart_scripts set `event_param4` = 13000 where `entryorguid` = 9707 and `ID` = 0;
Update smart_scripts set `target_type` = 1 where `entryorguid` = 9707;
-- Line below is a root so that the portal doesnt follow the npc
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES (9707, 0, 4, 0, 1, 0, 100, 2, 1000, 1000, 1000, 1000, 0, 11, 50095, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Scareshield Portal - Out of Comabat - Cast \'Self Root\'');``````

Tested using KurthosWoWs dev branch.

**Comment by HelloKitty** [comment]
@whammyresilience , @Cillez made a PR to fix these things. Can you go check them and see if it's working? Going to merge to staging to get it deployed.

**Comment by whammyresilience** [comment]
Confirming this is now working correctly. @Cillez
