### ISSUE TITLE
[WARRIOR] Slam doesnt pause swingtimer

### ISSUE THREAD

**Issue by Jaxson123** [NoxGaming/TrinityCore#140]
**Current behaviour:**

Slam doesnt stop your swingtimer during its casts, which means while your casting slam your swingtimer is still continuing to go off during that cast, its esp easy to notice with 1.5s cast time slam.
 
**Expected behaviour:**

Your swingtimer is supposed to be completely paused during the slam cast.

**Steps to reproduce the problem:**
1. install quartz
2. get a warrior on the ptr, pick up an 2h with atleast 3.00
3. cast slam and see how your autoswing gets through way earlier then its supposed to

you can also check this link from true/primalwow was the exact same issue:
https://truewow.org/bugs/view.php?id=4771

**Comment by HelloKitty** [comment]
That link is not public, copy paste the information if you can.

Was this resolved ever resolved on PrimalWoW?

**Comment by Glonz** [comment]
yes this was resolved on primalwow.


Description | The warrior Slam ability is supposed to pause the melee swing timer while it's casting, so that if the next queued auto-attack has 3 seconds left to go off, if you cast slam, when slam finishes casting the same autoattack still has 3 seconds left to go off. What happens instead is that the swing timer continues even through the slam cast. In the above situation, for instance, the autoattack goes off 1.5 seconds after slam has finished casting.

-Install an autoattack timer mod such as Quartz.-About 1.6 seconds before the next autoattack goes off, start casting slam-After slam finishes casting, wait 0.1 seconds.-The swing timer on your addon is overridden by a new one because the previously queued swing just went off (0.1 seconds after slam finished casting, when it should have been 1.6 seconds later)

Significantly increases DPS for arms warriors on primal wow (1.5 seconds slam cast) but makes the rotation really annoying.

3.0.2 (14-Oct-2008): Slam now suspends the weapon swing timer rather than resetting it.
http://wowwiki.wikia.com/wiki/Slam

**Comment by Jaxson123** [comment]
0004771: Slam does not pause swing timer
--
The warrior Slam ability is supposed to pause the melee swing timer while it's casting, so that if the next queued auto-attack has 3 seconds left to go off, if you cast slam, when slam finishes casting the same autoattack still has 3 seconds left to go off.What happens instead is that the swing timer continues even through the slam cast. In the above situation, for instance, the autoattack goes off 1.5 seconds after slam has finished casting.
-Install an autoattack timer mod such as Quartz.-About 1.6 seconds before the next autoattack goes off, start casting slam-After slam finishes casting, wait 0.1 seconds.-The swing timer on your addon is overridden by a new one because the previously queued swing just went off (0.1 seconds after slam finished casting, when it should have been 1.6 seconds later)
Significantly increases DPS for arms warriors on primal wow (1.5 seconds slam cast) but makes the rotation really annoying.

pretty much the same information and yea it got resolved on primal like glonz said

**Comment by Nyeriah** [comment]
https://github.com/NoxGaming/TrinityCore/commit/96e68c9883c0217211a22acd17d6f4bcacb9e749
